-- ============================================
-- RBAC Schema for Multi-Tenant SaaS
-- ============================================

-- 1. CUSTOM TYPES
-- ============================================

create type public.org_role as enum ('owner', 'admin', 'member', 'viewer');

create type public.org_permission as enum (
  -- Organization management
  'org.update',
  'org.delete',
  'org.billing',
  -- Member management
  'members.invite',
  'members.remove',
  'members.update_role',
  -- Projects (example resource)
  'projects.create',
  'projects.read',
  'projects.update',
  'projects.delete'
);


-- 2. ORGANIZATIONS TABLE
-- ============================================

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.organizations is 'Organizations/workspaces for multi-tenant isolation';


-- 3. ORGANIZATION MEMBERS (User <-> Org <-> Role)
-- ============================================

create table public.organization_members (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.org_role not null default 'member',
  created_at timestamptz not null default now(),

  unique(organization_id, user_id)
);

comment on table public.organization_members is 'Maps users to organizations with their role';


-- 4. ROLE PERMISSIONS (Static role -> permission mapping)
-- ============================================

create table public.role_permissions (
  id bigint generated by default as identity primary key,
  role public.org_role not null,
  permission public.org_permission not null,

  unique(role, permission)
);

comment on table public.role_permissions is 'Maps roles to their allowed permissions';


-- 5. USER PREFERENCES (Current org selection)
-- ============================================

create table public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  current_organization_id uuid references public.organizations(id) on delete set null,
  updated_at timestamptz not null default now()
);

comment on table public.user_preferences is 'User preferences including current organization selection';


-- 6. PROJECTS (Example tenant-scoped resource)
-- ============================================

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  description text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.projects is 'Example tenant-scoped resource';


-- 7. INDEXES (Critical for RLS performance)
-- ============================================

create index idx_org_members_user_id on public.organization_members(user_id);
create index idx_org_members_org_id on public.organization_members(organization_id);
create index idx_org_members_role on public.organization_members(role);
create index idx_projects_org_id on public.projects(organization_id);
create index idx_projects_created_by on public.projects(created_by);
create index idx_role_permissions_role on public.role_permissions(role);
create index idx_user_preferences_org on public.user_preferences(current_organization_id);


-- 8. UPDATED_AT TRIGGERS
-- ============================================

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger update_organizations_updated_at
  before update on public.organizations
  for each row execute function public.update_updated_at_column();

create trigger update_user_preferences_updated_at
  before update on public.user_preferences
  for each row execute function public.update_updated_at_column();

create trigger update_projects_updated_at
  before update on public.projects
  for each row execute function public.update_updated_at_column();
